# This GitHub Actions workflow runs all Python scripts in the scripts directory every 15 minutes
# using a self-hosted Windows runner.

name: Scheduled Python Scripts

on:
  schedule:
    - cron: "*/15 * * * *"  # run every 15 minutes
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Execute Python scripts
        run: |
          for file in scripts/*.py; do
            echo "Running $file"
            python "$file"
          done
        shell: bash
